config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root 'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # Mount Mission Control Job's engine where you wish to have it accessible
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :assemblees do
    collection do
      get :import
      post :import_do
    end
    member do
      get :envoyer_lien_gestionnaire
    end
  end
  resources :users
  resources :presences, only: %i[ index destroy ]
  resources :organisations, only: %i[ edit update ]
  resources :mail_logs, only: %i[ index show ]

  namespace :admin do
    get :index
    get :signature_collective
    post :signature_collective_do
    get :signature_individuelle
    post :signature_individuelle_do
    get :import
    post :import_do
    get :audits
    get :premium
    get :create_new_admin
    post :create_new_admin_do
    get :create_new_participant
    post :create_new_participant_do
    get :fake_signatures_detector
    get :fake_signature_detector
    get :launch_fake_signature_detector
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"

  # Defines the root path route ("/")
  root "presences#new"
end

app/models/presence.rb
class Presence < ApplicationRecord
  audited

  belongs_to :user
  belongs_to :assemblee

  validates :user_id, uniqueness: {scope: :assemblee_id, message: "Une seule signature par session !" } 
  validate :check_heure

  encrypts :signature

  scope :ordered, -> { order(heure: :desc) }

  after_create_commit -> { broadcast_prepend_to "presences_#{self.assemblee.organisation.slug}", 
                                                partial: "presences/presence", 
                                                locals: { presence: self }, 
                                                target: "presences" }

  after_create_commit -> { broadcast_replace_to "presences_count_#{self.assemblee.organisation.slug}", 
                                                partial: "presences/presences_count", 
                                                locals: { presences_count: self.assemblee.presences.count }, 
                                                target: "presences_count" }


  def check_heure
    if !(Time.current > self.assemblee.début - 10.minutes && Time.current < (self.assemblee.début + self.assemblee.durée.to_f.hours))
      self.errors.add :erreur, ": Le délai imparti a expiré !" 
    end
  end

  def check_conflit
    # Check si des session se passent au même moment, et si un participant a signé sur deux de ces sessions 
    assemblees = self.assemblee.organisation.assemblees.tagged_with(self.user.tags, any: true).where("(assemblees.début BETWEEN :debut AND :fin) OR (assemblees.fin BETWEEN :debut AND :fin) OR (:debut BETWEEN assemblees.début AND assemblees.fin)", {debut: self.assemblee.début, fin: self.assemblee.fin})
    return [((assemblees.count > 1)? assemblees.pluck(:id) : false) , (assemblees.joins(:presences).where('presences.user_id': self.user_id).count > 1)]
  end
  
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  before_action :set_presence, only: %i[ show edit update destroy ]
  before_action :is_user_authorized

  # GET /presences or /presences.json
  def index
    @presences = current_user.organisation.presences.ordered
    @assemblees = current_user.organisation.assemblees.order(:nom)
    @users = current_user.organisation.users
    @tags = @users.tag_counts_on(:tags).order(:taggings_count).reverse

    unless params[:tags].blank?
      @users = @users.tagged_with(params[:tags].reject(&:blank?))
      session[:tags] = params[:tags]
    else
      session[:tags] = params[:tags] = []
    end

    unless params[:search].blank?
      @users = @users.where("nom ILIKE :search OR prénom ILIKE :search OR email ILIKE :search", {search: "%#{params[:search]}%"})
    end

    users_presences_ids = []
    @users.each do |user|
      users_presences_ids << user.presences.pluck(:id)
    end
    @presences = @presences.where(id: users_presences_ids.flatten)

    if params[:assemblee_id].present?
      assemblee = Assemblee.find_by(id: params[:assemblee_id])
      @presences = @presences.where(assemblee_id: assemblee.id)
    end

    if params[:user_id].present?
      @presences = @presences.where(user_id: params[:user_id])      
    end

    respond_to do |format|
      format.html do 
      end

      format.xls do
        book = PresencesToXls.new(@presences).call
        file_contents = StringIO.new
        book.write file_contents # => Now file_contents contains the rendered file output
        filename = "Émargements_#{assemblee.try(:nom)}_#{DateTime.now}.xls"
        send_data file_contents.string.force_encoding('binary'), filename: filename 
      end

      format.pdf do
        pdf = PresencePdf.new
        pdf.rapport(@presences.joins(:user).reorder("users.nom"), assemblee)

        send_data pdf.render,
            filename: "Présences_#{assemblee.try(:nom)}_#{DateTime.now}.pdf",
            type: 'application/pdf',
            disposition: 'inline'
      end
    end
  end

  # GET /presences/1 or /presences/1.json
  def show
  end

  # GET /presences/new
  def new
    @presence = Presence.new
  end

  # GET /presences/1/edit
  def edit
  end

  # POST /presences or /presences.json
  def create
    @presence = Presence.new(presence_params)
    @presence.heure = DateTime.now
    @presence.user = current_user

    respond_to do |format|
      if @presence.save
        format.html { redirect_to new_presence_url, notice: "L'émargement a été créé avec succès." }
        format.json { render :show, status: :created, location: @presence }
      else
        format.html do
          @users = [] 
          render :new, status: :unprocessable_entity
        end
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presences/1 or /presences/1.json
  def update
    respond_to do |format|
      if @presence.update(presence_params)
        format.html { redirect_to presences_url, notice: "L'émargement a été modifié avec succès." }
        format.json { render :show, status: :ok, location: @presence }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presences/1 or /presences/1.json
  def destroy
    @presence.destroy!

    respond_to do |format|
      format.html { redirect_to presences_url, notice: "L'émargement a été supprimé avec succès." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presence
      @presence = Presence.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def presence_params
      params.require(:presence).permit(:signature)
    end

    def is_user_authorized
      authorize @presence? @presence : Presence
    end
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/views/presences/_form.html.erb
<%= form_with(model: presence) do |form| %>
  <% if presence.errors.any? %>
    <div style="color: red">
      <ul>
        <% presence.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if presence.assemblee %>
    <% if p = presence.assemblee.presences.where(user_id: current_user.id).first %>
      <p>Vous avez signé il y a <%= time_ago_in_words p.created_at %></p>
    <% else %>
      <div>
        <%= form.label :signature, style: "display: block" %>
        <%= form.text_field :signature, style:'display: none' %>
      </div>

      <div id="signature">
        <div class="wrapper">
          <canvas id="signature-pad" class="signature-pad border border-slate-300" width=700 height=350></canvas>
        </div>

        <% if ((presence.assemblee.début + presence.assemblee.durée.to_f.hours) - Time.current).positive? %>
          <p class="mt-2">
            Temps restant :
            <time data-controller="timeago" data-timeago-datetime-value="<%= @presence.assemblee.fin %>" data-timeago-refresh-interval-value="60000"></time>.
          </p>
        <% end %>

        <div class="flex gap-4 mt-4">
          <button id="save" class="btn btn-primary btn-outline btn-lg">Enregistrer</button>
          <a id="clear" class="btn btn-lg">Effacer</a>
        </div>
      </div>
    <% end %>
  <% elsif @assemblée_future %>
    <p>
      La prochaine session commencera le <%= l(@assemblée_future.début, format: :long) %>
      <br>
      Voici comment vous y rendre <%= link_to "ici", "https://www.fluo.eu/fr/itineraires/4/TripPlanner/index?KeywordDep=HAGUENAU%20-%20Haguenau&PointDep=3029159_1&LatDep=48%2C81439018&LngDep=7%2C7891794&KeywordArr=STRASBOURG%20-%20Strasbourg&PointArr=3029435_1&LatArr=48%2C58509906&LngArr=7%2C7369193&Date=13%2F02%2F2024&TypeDate=65&Hour=16&Minute=50&Algorithm=Fastest&TypeTrip=PlanTrip&IgnoreDisruptions=False&WalkDistance=2000&WalkSpeed=5&CarDistance=25&CarLeave=0&BikeDistance=10&BikeLeave=0&BikeSpeed=15&Accessibility=0&IsoBefore=True&IsSeveralNetworks=False&Submit=False&ExpandCriteria=0&ListModes=Bus%7CCoach%7CMetro%7CTram%7CTod%7CTrain%7CTgv%7CTer%7CSchool&ListPartners=22%7C47%7C57%7C43%7C56%7C51%7C53%7C52%7C61%7C42%7C45%7C50%7C58%7C49%7C44%7C46%7C6%7C60%7C8%7C4%7C39%7C2%7C7%7C11%7C21%7C23%7C15%7C63%7C9%7C41%7C17%7C40%7C59%7C20%7C14%7C18%7C12%7C19%7C16%7C24%7C26%7C30%7C31%7C32%7C25%7C27%7C28%7C29%7C3%7C13%7C5%7C64%7C55%7C54%7C33&Length=11&_=1707830182242", target: "_blank", class: "text-primary hover:underline" %>
    </p>
  <% else %>
    <p>Il n'y a pas de session en cours</p>
  <% end %>
<% end %>

<script>
  var signaturePad = new SignaturePad(document.getElementById('signature-pad'));
  var signatureField = document.getElementById('presence_signature');
  var saveButton = document.getElementById('save');
  var cancelButton = document.getElementById('clear');

  saveButton.addEventListener('click', function (event) {
    if (signaturePad.isEmpty()){
      event.preventDefault();
    } else {
      signatureField.setAttribute('value', signaturePad.toDataURL("image/svg+xml"));
    }
  });

  cancelButton.addEventListener('click', function (event) {
    signaturePad.clear();
  });

  // slimselect
  new SlimSelect({
    select: '#presence_user_id',
    settings: {
      searchPlaceholder: 'Recherche',
      searchText: 'Pas de résultat',
      searchingText: 'Recherche...',
    }
  })
</script>

app/views/presences/_presence.html.erb
<div id="<%= dom_id presence %>" class="flex flex-col shadow p-4 hover:shadow-xl ease-out duration-500 gap-2 mt-4">
  <div>
    <small class="italic text-secondary">
      <i>Il y a <%= time_ago_in_words presence.heure %></i>
    </small>

    <p class="text-2xl text-primary"><%= presence.user.nom %></p>

    <p class="text-xl">
      <%= presence.assemblee.nom.humanize %>
    </p>

    <p class="text-secondary">
      <%= presence.assemblee.horaires_medium %>
    </p>
  </div>
  
  <img src=<%= presence.signature %> style="padding: 10px; height:125px">
  
  <%= button_to presence, method: :delete, data: {turbo_confirm: "Êtes-vous certain(e) de vouloir supprimer cet émargement ?" }, class:'text-base-300 hover:text-error float-end' do %>
    <span class="material-symbols-outlined">
      delete
    </span>
  <% end %>
</div>

app/views/presences/_presences_count.html.erb
<div id="presences_count" class="mt-8 mb-2">
    Affichage de <%= pluralize(presences_count, 'émargement', plural: 'émargements') %>
    au total (<%= l DateTime.now  %>)
</div>

app/views/presences/edit.html.erb
<h1 class="text-4xl font-bold mb-6">Modification Émargement</h1>

<%= render "form", presence: @presence %>

<br>

<%= link_to "Retour", presences_path, class:'btn btn-sm' %>

app/views/presences/index.html.erb
<h1 class="text-4xl font-bold mb-4"><%= page_title!("Liste des émargements") %></h1>

<%= form_tag request.path, method: :get do %>
  <div class="flex flex-wrap items-end gap-4">
    <div class="max-w-72">
      <%= label_tag :search, "Rechercher" %>
      <%= text_field_tag :search, params[:search], include_blank:true, onchange:'this.form.submit()', class: 'input input-bordered input-sm w-full', placeholder: 'Nom/Prénom/Email' %>
    </div>
    <div class="max-w-md w-full">
      <%= label_tag :assemblee_id, "Session" %>
      <%= select_tag :assemblee_id, options_from_collection_for_select(@assemblees, :id, :nom_long, params[:assemblee_id]), include_blank: true, onchange: 'this.form.submit()' %>
    </div>
    <div class="max-w-md w-full">
      <%= label_tag :user_id, "Participant" %>
      <%= select_tag :user_id, options_from_collection_for_select(@users, :id, :nom_prénom, params[:user_id]), include_blank: true, onchange: 'this.form.submit()' %>
    </div>
    <div>
      <%= render TagCloudComponent.new(tags: @tags) %>
    </div>
  </div>
<% end %>

<div class="divider"></div>

<div id="presences" class="flex flex-wrap gap-4 mb-12">
  <%= turbo_stream_from "presences_#{current_user.organisation.slug}" %>
  <%= render @presences %>
</div>

<%= turbo_stream_from "presences_count_#{current_user.organisation.slug}" %>

<div id="presences_count" class="mt-8 mb-2">
  Affichage de <%= pluralize(@presences.count, 'émargement', plural: 'émargements') %>
</div>  

<%= link_to url_for(params.permit!.merge(format: :xls)), class: "text-success hover:underline" do %>
  Exporter vers Excel
<% end %>

<% if params[:assemblee_id].present? %>
  |
  <%= link_to url_for(params.permit!.merge(format: :pdf)), class: "text-error hover:underline mb-12" do %>
    Exporter vers PDF
  <% end %>
<% end %>

<script>
  new SlimSelect({
    select: '#assemblee_id',
    settings: {
      searchPlaceholder: 'Recherche',
      searchText: 'Pas de résultat',
      searchingText: 'Recherche...',
      placeholderText: 'Filtrer par session',
      allowDeselect: true
    }
  })
  new SlimSelect({
    select: '#user_id',
    settings: {
      searchPlaceholder: 'Recherche',
      searchText: 'Pas de résultat',
      searchingText: 'Recherche...',
      placeholderText: 'Filtrer par participant',
      allowDeselect: true
    }
  })
</script>

app/views/presences/new.html.erb
<h1 class="text-4xl font-bold mb-6">Émargement</h1>

<%= render "form", presence: @presence %>

app/views/presences/show.html.erb
<%= render @presence %>

<div>
  <%= link_to "Modifier", edit_presence_path(@presence), class:'btn btn-primary btn-sm' %> |
  <%= link_to "Retour", presences_path, class:'btn btn-sm' %>

  <%= button_to "Supprimer", @presence, method: :delete, class:'btn btn-error btn-sm' %>
</div>