config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root 'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # Mount Mission Control Job's engine where you wish to have it accessible
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :assemblees do
    collection do
      get :import
      post :import_do
    end
    member do
      get :envoyer_lien_gestionnaire
    end
  end
  resources :users
  resources :presences, only: %i[ index destroy ]
  resources :organisations, only: %i[ edit update ]
  resources :mail_logs, only: %i[ index show ]

  namespace :admin do
    get :index
    get :signature_collective
    post :signature_collective_do
    get :signature_individuelle
    post :signature_individuelle_do
    get :import
    post :import_do
    get :audits
    get :premium
    get :create_new_admin
    post :create_new_admin_do
    get :create_new_participant
    post :create_new_participant_do
    get :fake_signatures_detector
    get :fake_signature_detector
    get :launch_fake_signature_detector
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"

  # Defines the root path route ("/")
  root "presences#new"
end

app/views/admin/_audit.html.erb
<tr class="hover">
  <td>
    Il y a <%= time_ago_in_words(audit.created_at) %>
    <br>
    (<%= l(audit.created_at, format: :custom) %>)
  </td>
  <td>
    <%= audit.user.email %>
    (#<%= audit.user.id %>)
    <br>
    <%= 'Admin' if audit.user.admin? %>
    <br>
    IP: <%= audit.remote_address %>
  </td>
  <td>
    <%= audit.auditable_type %>
  </td>
  <td style="text-align: right;">
    <%= link_to_if audited_view_path(audit), audit.auditable_id, audited_view_path(audit), class: 'text-primary hover:underline' %>
  </td>
  <td>
    <%= audit.action.humanize %>
  </td>
  <td>
    <% unless audit.comment %>
      <%= sanitize prettify(audit).join('<br>') %>
    <% else %>
      <%= audit.comment %>
    <% end %>
  </td>
</tr>

app/views/admin/audits.html.erb
<h1 class="text-4xl font-bold mb-4">
  <%= page_title!("Audit des modifications") %>
</h1>

<%= form_tag request.path, method: :get do %>
  <div class="flex flex-wrap items-end gap-4">

    <div class="w-full sm:w-1/6 pr-4">
      <%= label_tag :start_date, "Du" %>    
      <%= text_field_tag :start_date, params[:start_date], type:'date', class:"input input-bordered input-sm w-full" %>
    </div>

    <div class="w-full sm:w-1/6 pr-4">
      <%= label_tag :end_date, "Au" %>    
      <%= text_field_tag :end_date, params[:end_date], type:'date', class:"input input-bordered input-sm w-full", onchange:'this.form.submit()' %>
    </div>

    <div class="w-full sm:w-1/6 pr-4">
      <%= label_tag :type, "Type" %>
      <%= select_tag :type,
            options_for_select(@types, params[:type]), include_blank:true, onchange:'this.form.submit()', class:"select select-bordered select-sm w-full" %>
    </div>

    <div class="w-full sm:w-1/12 pr-4">
      <%= label_tag :action_name, "Action" %>
      <%= select_tag :action_name,
            options_for_select(@actions, params[:action_name]), include_blank:true, onchange:'this.form.submit()', class:"select select-bordered select-sm w-full" %>
    </div>

    <div class="w-full sm:w-1/5 pr-4">
      <%= label_tag :search, "Rechercher" %>      
      <%= text_field_tag :search, params[:search], onchange:'this.form.submit()', class:"input input-bordered input-sm w-full" %>
    </div>   
  </div>
<% end %>

<div class="divider"></div>

<div class="overflow-x-auto mt-8">
  <table class="table table-sm">
    <thead class="bg-slate-100">
      <tr>
        <th>Date</th>
        <th>Utilisateur</th>
        <th>Type</th>
        <th>Id</th>
        <th>Action</th>
        <th>Modifications</th>
      </tr>
    </thead>

    <%= render partial: 'audit', collection: @audits %>

    <tfoot>
      <tr>
        <tr colspan="6"></tr>
      </tr>
    </tfoot>

  </table>
</div>

<div class="my-6">
  <%== pagy_info(@pagy) %>
  <%== pagy_nav(@pagy) %>
</div>

app/views/admin/create_new_admin.html.erb
<div class="mx-auto md:w-1/3 w-full">

  <h1 class="text-4xl font-bold mb-6"><%= page_title!("Ajouter un Administrateur") %></h1>

  <div class="max-w-96">
    <%= form_with(model: @user, class: "contents", url: "create_new_admin_do", html: { autocomplete: "off" }) do |form| %>
      <% if @user.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
          <h2><%= pluralize(@user.errors.count, "erreur") %> empêche(nt) cet administrateur d'être enregistré :</h2>

          <ul>
            <% @user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :nom, style: "display: block" %>
        <%= form.text_field :nom, class: 'input input-bordered input-sm w-full', required: true %>
      </div>

      <div class="mt-4">
        <%= form.label :prénom, style: "display: block" %>
        <%= form.text_field :prénom, class: 'input input-bordered input-sm w-full', required: true %>
      </div>

      <div class="mt-4">
        <%= form.label :email, style: "display: block" %>
        <%= form.email_field :email, class: 'input input-bordered input-sm w-full', required: true %>
      </div>

      <div class="mt-4">
        <%= form.label :password, style: "display: block" %>
        <%= form.password_field :password, class: 'input input-bordered input-sm w-full', required: true %>
      </div>
      <div class="mt-4">
        <%= form.label :password_confirmation, style: "display: block" %>
        <%= form.password_field :password_confirmation, class: 'input input-bordered input-sm w-full', required: true %>
      </div>

      <div class="inline">
        <%= form.submit "Enregistrer", class: "btn btn-primary btn-outline w-full my-4" %>
        <%= link_to "Retour", admin_index_path, class: "link" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/create_new_participant.html.erb
<div class="mx-auto md:w-1/3 w-full">

  <h1 class="text-4xl font-bold mb-6"><%= page_title!("Ajouter un Participant") %></h1>

  <div class="max-w-96">
    <%= form_with(model: @user, class: "contents", url: "create_new_participant_do", html: { autocomplete: "off" }) do |form| %>
      <% if @user.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
          <h2><%= pluralize(@user.errors.count, "erreur") %> empêche(nt) ce participant d'être enregistré :</h2>

          <ul>
            <% @user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div>
        <%= form.label :nom, style: "display: block" %>
        <%= form.text_field :nom, class: 'input input-bordered input-sm w-full', required: true %>
      </div>

      <div class="mt-4">
        <%= form.label :prénom, style: "display: block" %>
        <%= form.text_field :prénom, class: 'input input-bordered input-sm w-full', required: true %>
      </div>

      <div class="mt-4">
        <%= form.label :email, style: "display: block" %>
        <%= form.email_field :email, class: 'input input-bordered input-sm w-full', required: true %>
      </div>

      <div class="my-4">
        <%= form.label :tags, "Groupes d'intérêt", style: "display: block" %>
        <%= form.select :tags, options_from_collection_for_select(@tags, :name, :name), multiple: true %>
      </div>

      <div class="inline">
        <%= form.submit "Enregistrer", class: "btn btn-primary btn-outline w-full my-4" %>
        <%= link_to "Retour", admin_index_path, class: "link" %>
      </div>
    <% end %>
  </div>
</div>

<script>
  // slimselect
  new SlimSelect({
    select: '#user_tags',
    settings: {
      searchPlaceholder: 'Recherche',
      searchText: 'Pas de résultat',
      searchingText: 'Recherche...',
      placeholderText: 'Choisissez un ou plusieurs groupes',
      allowDeselect: true,
    },
    events: {
      addable: function (value) {
        return value
      }
    }
  })
</script>

app/views/admin/fake_signature_detector.html.erb
<h1 class="text-4xl font-bold text-primary mb-6"><%= page_title!("Détection de fausses signatures") %></h1>

<div class="flex gap-4 items-center mb-4">
  <p><%= time_ago_in_words(Time.at(@batch_prediction_job.create_time.seconds)) %></p>
  <p class="font-black"><%= link_to @batch_prediction_job.display_name, admin_fake_signature_detector_path(batch_prediction_job: @batch_prediction_job.name.split('batchPredictionJobs/').last) %></p>
  <p>
    <span class="material-symbols-outlined text-<%= @batch_prediction_job.state.to_s.include?("SUCCEEDED") ? "success" : @batch_prediction_job.state.to_s.include?("FAILED") ? "error" : "secondary" %> px-4">
      <%= @batch_prediction_job.state.to_s.include?("SUCCEEDED") ? "check_circle" : @batch_prediction_job.state.to_s.include?("FAILED") ? "error" : "stop_circle" %>
    </span>
  </p>
  <p><%= l Time.at(@batch_prediction_job.create_time.seconds) %></p>
  <p><%= ((@batch_prediction_job.end_time.seconds - @batch_prediction_job.create_time.seconds)/ 1.minutes) %> minutes</p>
  <p><%= @batch_prediction_job.completion_stats.successful_count %> réussies / <%= @batch_prediction_job.completion_stats.failed_count %> échouées</p>
</div>

<div class="divider mb-4"></div>

<% @downloaded.read.split(' ').each do |line| %>
  <% presence = Presence.find_by(id: line.split("signature_").last.split("_assemblee").first)%>
  <div class="flex gap-8 mb-8">
    <% if presence %>
      <div>
        <p class="text-2xl font-bold text-primary"><%= presence.user.nom_prénom %></p>
        <p>
          <%= presence.assemblee.nom.humanize %>
          / <%= l(presence.assemblee.début, format: :long) %>
        </p>
        <%= image_tag presence.signature %>
      </div>
    <% end %>
    <div>
      <% json = JSON.parse(line)['prediction'] %>
      <div class="flex gap-4">
        <% json['displayNames'].length.times do |i| %>
          <div class="<%= 'font-black text-success' if i.zero? && json['confidences'][i] > 0.8 %>">
            <p><%= json['displayNames'][i] %></p>
            <p><%= (json['confidences'][i] * 100).round(2) %>%</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="divider mb-4"></div>
<% end %>

app/views/admin/fake_signatures_detector.html.erb
<div class="flex flex-wrap justify-between mb-4">
  <h1 class="text-4xl font-bold mb-4">
    <%= page_title!("Historique des détections") %>
  </h1>
  
  <%= link_to "Lancer détection", admin_launch_fake_signature_detector_path, class:'btn btn-primary btn-outline btn-lg hover:shadow-xl hover:!text-white' %>
</div>

<div class="overflow-x-auto">
  <table class="table table-sm">
    <thead class="bg-slate-100">
      <tr>
        <th>Il y a</th>
        <th>Nom</th>
        <th>État</th>
        <th>Créé le</th>
        <th>Durée</th>
        <th>Prédictions traités</th>
      </tr>
    </thead>
    <tbody>
      <% @batch_prediction_jobs.each do |response| %>
        <tr>
          <td><%= time_ago_in_words(Time.at(response.create_time.seconds)) %></td>
          <td class="font-black text-primary hover:underline"><%= link_to_if response.state.to_s.include?("SUCCEEDED"), response.display_name, admin_fake_signature_detector_path(batch_prediction_job: response.name.split('batchPredictionJobs/').last) %></td>
          <td>
            <span class="material-symbols-outlined text-<%= response.state.to_s.include?("SUCCEEDED") ? "success" : response.state.to_s.include?("FAILED") ? "error" : response.state.to_s.include?("RUNNING") ? "primary" : "secondary" %>">
              <%= response.state.to_s.include?("SUCCEEDED") ? "check_circle" : response.state.to_s.include?("FAILED") ? "error" : response.state.to_s.include?("RUNNING") ? "timelapse" : "stop_circle" %>
            </span>
          </td>
          <td><%= l Time.at(response.create_time.seconds) %></td>
          <td><%= ((response.end_time.seconds - response.create_time.seconds)/ 1.minutes) if response.end_time%> minutes</td>
          <td><%= response.completion_stats.successful_count %> réussies / <%= response.completion_stats.failed_count %> échouées</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/import.html.erb
<div class="mx-auto md:w-1/3 w-full">
  <h1 class="text-4xl font-bold text-nowrap mb-6"><%= page_title!("Importer des Participants") %></h1>

  <%= form_tag({action: "import_do", method: :post}, multipart: true) do %>
    <div>
      <%= label_tag :content, "Adresses emails des participants à créer" %>
      <%= text_area_tag :content, nil, 
                        rows: 7, 
                        class:"textarea textarea-bordered textarea-sm w-full shadow", 
                        required: true, 
                        placeholder: "annette.bonvoisin@orange.fr\r\njacques.boulanger@free.fr\r\nla_moustache@gmail.com;KATHERINE;Philippe" %>
      <label>
        <span class="label-text-alt">
          Les adresses doivent être séparées par un retour à la ligne. Elles peuvent être suivies du nom et du prénom, séparés par une virgule ou un point-virgule.
          <br>
          Un message sera envoyé à chaque participant afin de confirmer son adresse email.
        </span>
      </label>
      <br>
      <% unless current_user.organisation.premium %>
        <span class="label-text-alt">
          Le nombre de participants dans l'organisation est limité à 50. Passez au <%= link_to "Compte PREMIUM", admin_premium_path, class: 'text-primary hover:underline' %> pour être en illimité.
        </span>
      <% end %>
    </div>
    
    <div class="mt-4">
      <%= label_tag :groupes, "Associer ces participants à des groupes d'intérêt" %>
      <%= select_tag :groupes, options_from_collection_for_select(@tags, :name, :name), multiple: true %>
      <div class="label">
        <span class="label-text-alt">
          Pour associer ces participants à des groupes d'intérêt, 
          existants ou non. Pour ajouter un nouveau groupe; entrez son nom 
          et cliquez sur [+]
        </span>
      </div>
    </div>

    <div>
      <%= submit_tag "Lancer l'importation", class: "btn btn-primary btn-outline w-full my-4", 'data-turbo': false %>
      <%= link_to "Retour", admin_index_path, class: "link" %>
    </div>
  <% end %>

</div>

<script>
  // slimselect
  new SlimSelect({
    select: '#groupes',
    settings: {
      searchPlaceholder: 'Recherche',
      searchText: 'Pas de résultat',
      searchingText: 'Recherche...',
      placeholderText: 'Choisissez un ou plusieurs groupes',
      allowDeselect: true,
    },
    events: {
      addable: function (value) {
        return value
      }
    }
  })
</script>

app/views/admin/index.html.erb
<div class="overflow-x-auto">
  <div class="flex justify-center mt-4">
    <div class="flex flex-col items-center">
      <h1 class="text-3xl font-bold mb-8">
        Chronologie des prochaines sessions
      </h1>

      <% if @assemblees.any? %>
        <ul class="timeline mb-8">
          <% @assemblees.each_with_index do |assemblee, index| %>
            <% started = (assemblee.début < DateTime.now) %>
            <% finished = (assemblee.fin < DateTime.now) %>
            <li>
              <hr class="<%= 'bg-primary' if started %>"/>
              <%= render partial: "partials/timeline_box", locals: {assemblee:, start: index.even?} if index.even? %>
              <div class="timeline-middle">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5 <%= 'text-primary' if started %>">
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
                </svg>
              </div>
              <%= render partial: "partials/timeline_box", locals: {assemblee:, start: index.even?} if index.odd? %>
              <hr class="<%= 'bg-primary' if finished %>"/>
            </li>
          <% end %>
        </ul>
      <% else %>
        <div class="my-12 shadow">
          <%= link_to "Créer une nouvelle session", new_assemblee_path, class:'btn btn-success btn-outline btn-lg hover:shadow-xl hover:!text-white' %>
        </div>
      <% end %>

      <div class="divider"></div>
    </div>
  </div>
</div>

<div class="my-4">
  <div class="flex justify-center mb-4">
    <%= link_to "ÉMARGEMENTS", presences_path, class: 'btn btn-outline btn-primary btn-lg hover:!text-white w-1/2' %>
  </div>
  <div class="flex justify-center mb-4">
    <%= link_to "PARTICIPANTS", users_path, class: 'btn btn-outline btn-primary btn-lg hover:!text-white w-1/2' %>
  </div>
  <div class="flex justify-center mb-4">
    <%= link_to "SESSIONS", assemblees_path, class: 'btn btn-outline btn-primary btn-lg hover:!text-white w-1/2' %>
  </div>
  <div class="flex justify-center gap-1">
    <%= link_to "Mon organisation", edit_organisation_path(current_user.organisation), title: "Voir les paramètres de mon Organisation", class: 'btn btn-outline btn-secondary hover:!text-white' %>
    <%= link_to "Mail logs", mail_logs_path, title: "Historique des mails envoyés", class: 'btn btn-outline btn-secondary hover:!text-white' %>
    <%= link_to "Audit trail", admin_audits_path, title: "Audit des modifications", class: 'btn btn-outline btn-secondary hover:!text-white' %>
    <%= link_to "Détections d'anomalies", admin_fake_signatures_detector_path, title: "Détections de fausses signatures", class: 'btn btn-outline btn-secondary hover:!text-white' %>
  </div>
</div>

app/views/admin/premium.html.erb
<h1 class="text-4xl font-bold my-8 text-center">
  <%= page_title!("Offre PREMIUM") %>
  <span class="material-symbols-outlined text-primary">
    verified
  </span>
</h1>

<div class="flex flex-wrap justify-center">
  <div class="card bg-base-100 shadow-lg">
    <div class="card-body">
      <h2 class="text-center font-black text-2xl mb-8">
        <% if current_user.premium? && current_user.organisation.expiration_premium %>
          <span class="text-gray-500">
            Vos avantages jusqu'au 
            <%= l current_user.organisation.expiration_premium, format: :custom2 %>
          </span>
        <% else %>
          <span class="text-primary">
            Tous les avantages d'avoir un compte 'PREMIUM' :
          </span>
        <% end %>
      </h2>

      <p>
        <span class="badge badge-primary badge-xs"></span> 
        Nombre de participants <b>illimité</b> (au lieu de 50 avec l'offre gratuite)  
      </p>
      <p>
        <span class="badge badge-primary badge-xs"></span> 
        <b>Support technique</b> par email à J+1
      </p>
      <p>
        <span class="badge badge-primary badge-xs"></span> 
        Accès à l'AUDIT TRAIL, <b>historique des modifications</b> de données (assemblées, participants, signatures, connexions, ...)
      </p>
      <p>
        <span class="badge badge-primary badge-xs"></span> 
        MAIL LOGS : <b>conservation permanente des statuts</b> d'acheminement et d'ouverture des emails envoyés.
      </p>
      <p>
        <span class="badge badge-primary badge-xs"></span> 
        <b>Détections des anomalies par l'IA (fausses signatures, usages inhabituels, etc.)</b>
      </p>
      <p>
        <span class="badge badge-primary badge-xs"></span> 
        Tarif unique : 99 €/Année/Organisation
      </p>

      <%= link_to "Nous contacter", "https://www.philnoug.com/contact?objet=Émargements", class: 'mt-6 underline text-2xl text-primary', target:"_blank" %>
    </div>
  </div>
</div>

app/views/admin/signature_collective.html.erb
<h1 class="text-2xl sm:text-4xl font-bold text-primary mt-6">
  <%= page_title!(@presence.assemblee.nom.humanize) %>
</h1>

<p class="font-bold">
  <%= @presence.assemblee.horaires_long %>
  <% if @presence.assemblee.début > DateTime.now %>
    <span class="text-warning">
      (début de session dans <%= time_ago_in_words @presence.assemblee.début %>)
    </span>
  <% elsif @presence.assemblee.in_progress? %>
    <span class="text-error">
      (fin de session dans <%= time_ago_in_words @presence.assemblee.fin %>)
    </span>
  <% end %>
</p>

<p class="my-4">
  Groupes : <% @presence.assemblee.tags.each do |tag| %>
    <span class="badge"><%= tag.name.humanize %></span>
  <% end %>
</p>

<%= form_tag({action: "signature_collective_do", method: :post}) do %>
  <% if @presence.assemblee.in_progress? %>
    <%= hidden_field_tag :assemblee_id, params[:assemblee_id] %>
    <div class="flex flex-wrap gap-8 sm:gap-24">
      <% if @users_not_signed.any? %>
        <div class="flex-1 flex flex-col">
          <% if @presence.errors.any? %>
            <div style="color: red">
              <%= @presence.errors.full_messages %>
            </div>
          <% end %>
          <div class="mb-4 w-full sm:max-w-96">
            <%= label_tag :user_id, "Participant (Choisir votre nom dans la liste)", style: "display: block" %>
            <%= select_tag :user_id, options_from_collection_for_select(@users_not_signed, :slug, :nom_prénom), include_blank: true, required:true, class: 'input input-lg' %>
          </div>

          <div>
            <div>
              <%= label_tag :signature, "Signature (Merci de signer dans le cadre ci-dessous)", style: "display: block;"  %>
              <%= text_field_tag :signature, "", style:'display: none' %>
            </div>

            <div id="signature-container" class="sm:pr-8">
              <% if request.variant.include?(:phone) %>
                <canvas id="signature-pad" class="signature-pad bg-slate-100 shadow" width=300 height=150></canvas>
              <% else %>
                <canvas id="signature-pad" class="signature-pad bg-slate-100 shadow-xl" width=600 height=300></canvas>
              <% end %>

              <div class="flex flex-wrap gap-4 mt-8">
                <button id="save" class="btn btn-primary btn-outline hover:shadow-xl hover:!text-white btn-lg">Enregistrer cet émargement</button>
                <div id="clear" class="btn btn-lg btn-outline text-secondary" title="Effacer la signature">
                  <span class="material-symbols-outlined">
                    ink_eraser
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <h1 class="text-2xl text-success">
          Emargement complet !
          <br>
          Tous les participants à cette session ont déjà émargé
          <p class="my-4">
            <%= link_to "Voir les émargements", presences_path(assemblee_id: @presence.assemblee.id), class: 'btn btn-outline text-primary hover:underline'%>
          </p>
        </h1>

      <% end%>

      <div class="flex-1">
        <% if @presence.assemblee.presences.any? %>
          <h2 class="text-2xl text-secondary mb-4">Derniers émargements enregistrés</h2>
          <% @presence.assemblee.presences.order(created_at: :desc).each do |p| %>
            <i><%= p.user.nom_prénom %> a signé il y a <%= time_ago_in_words p.created_at%></i>
            <br>
          <% end %>
        <% end %>
      </div>
    </div>
  <% elsif @presence.assemblee.début > DateTime.now %>
    <p>La session n'a pas encore commencé. Vous pourrez émarger à partir du <%= l @presence.assemblee.début.to_date %> à <%= (@presence.assemblee.début - 10.minutes).strftime("%H:%M") %></p>
  <% else %>
    <p>Cette session est maintenant terminée.</p>
  <% end %>
<% end %>

<script>
  var signaturePad = new SignaturePad(document.getElementById('signature-pad'));
  var signatureField = document.getElementById('signature');
  var saveButton = document.getElementById('save');
  var cancelButton = document.getElementById('clear');

  //console.log(signaturePad);
  //console.log(signatureField);

  saveButton.addEventListener('click', function (event) {
    if (signaturePad.isEmpty()){
      event.preventDefault();
    } else {
      signatureField.setAttribute('value', signaturePad.toDataURL("image/svg+xml"));
    }
  });

  cancelButton.addEventListener('click', function (event) {
    signaturePad.clear();
  });

  // slimselect
  new SlimSelect({
    select: '#user_id',
    settings: {
      searchPlaceholder: 'Recherche',
      searchText: 'Pas de résultat',
      searchingText: 'Recherche...',
      placeholderText: 'Choisissez votre nom dans la liste',
      allowDeselect: true,
    }
  })
</script>