config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root 'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # Mount Mission Control Job's engine where you wish to have it accessible
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :assemblees do
    collection do
      get :import
      post :import_do
    end
    member do
      get :envoyer_lien_gestionnaire
    end
  end
  resources :users
  resources :presences, only: %i[ index destroy ]
  resources :organisations, only: %i[ edit update ]
  resources :mail_logs, only: %i[ index show ]

  namespace :admin do
    get :index
    get :signature_collective
    post :signature_collective_do
    get :signature_individuelle
    post :signature_individuelle_do
    get :import
    post :import_do
    get :audits
    get :premium
    get :create_new_admin
    post :create_new_admin_do
    get :create_new_participant
    post :create_new_participant_do
    get :fake_signatures_detector
    get :fake_signature_detector
    get :launch_fake_signature_detector
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"

  # Defines the root path route ("/")
  root "presences#new"
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  audited

  # Include default devise modules. Others available are:
  # :lockable,  :timeoutable,

  devise  :database_authenticatable,
          :recoverable,
          :validatable,
          :trackable,
          :registerable,
          :rememberable,
          :confirmable,
          :omniauthable,
          omniauth_providers: [:google_oauth2]

  acts_as_taggable_on :tags

  belongs_to :organisation, optional: true
  has_many :presences

  normalizes :nom, with: -> nom { nom.upcase.strip }
  normalizes :prénom, with: -> prénom { prénom.humanize.strip }

  scope :ordered, -> { order(:nom) }

  def nom_prénom
    "#{self.nom} #{self.prénom}"
  end

  def prénom_nom
    "#{self.prénom} #{self.nom}"
  end

  def dispatch_email_to_nom_prénom
    nom_prénom = self.email.split('@').first
    self.nom, self.prénom = nom_prénom.split('.')
  end

  def premium?
    self.organisation.premium?
  end

  def super_admin?
    %w[philippe.nougaillon@gmail.com pierreemmanuel.dacquet@gmail.com].include?(self.email)
  end

  def self.from_omniauth(auth)
    require "open-uri"

    if user = User.find_by(email: auth.info.email)
      user
    else
      find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.password_confirmation = user.password
        user.nom = auth.info.last_name   # assuming the user model has a name
        user.prénom = auth.info.first_name   # assuming the user model has a name
        user.organisation = Organisation.create(nom: "Mon_organisation")
        user.admin = true
        # user.tag_list.add("Gestionnaire")

        # If you are using confirmable and the provider(s) you use validate emails, 
        # uncomment the line below to skip the confirmation emails.
        user.skip_confirmation!

        UserMailer.welcome(user).deliver_now if user.save

        user
      end
    end
  end

  private

  def slug_candidates
    [SecureRandom.uuid]
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    # Associer l'utilisateur à une organisation
    @user.organisation = Organisation.create(nom: "Mon_organisation")
    @user.admin = true
    @user.dispatch_email_to_nom_prénom
    @user.save
    Events.instance.publish('organisation.created', payload: {user_id: @user.id})
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:organisation_id])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    admin_index_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :is_user_authorized
  before_action :set_tags, only: %i[ new edit ]

  # GET /users or /users.json
  def index
    @users = current_user.organisation.users.ordered

    @tags = @users.tag_counts_on(:tags).order(:taggings_count).reverse

    @assemblees = current_user.organisation.assemblees.order(:nom)

    unless params[:tags].blank?
      @users = @users.tagged_with(params[:tags].reject(&:blank?))
      session[:tags] = params[:tags]
    else
      session[:tags] = params[:tags] = []
    end

    unless params[:assemblee_id].blank?
      @users = @users.where(id: Assemblee.find(params[:assemblee_id]).related_users)
    end

    unless params[:search].blank?
      @users = @users.where("nom ILIKE :search OR prénom ILIKE :search OR email ILIKE :search", {search: "%#{params[:search]}%"})
    end

    # if params[:admin] == "on"
    #   @users = @users.where(admin: true)
    # end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.tag_list.add(params[:user][:tag_list])
    @user.organisation = current_user.organisation

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "Participant créé avec succès." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        @user.tag_list = params[:user][:tag_list]
        @user.save
        format.html { redirect_to user_url(@user), notice: "Participant modifié avec succès." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "Participant supprimé avec succès." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(slug: params[:id])
    end

    def set_tags
      @tags = current_user.organisation.tags 
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:nom, :prénom, :email, :adresse, :tag_list, :password)
    end

    def is_user_authorized
      authorize @user ? @user : User
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "erreur") %> empêche(nt) ce participant d'être enregistré :</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :nom, class: 'input input-bordered input-sm w-full', required: true %>
  </div>

  <div class="mt-4">
    <%= form.label :prénom, style: "display: block" %>
    <%= form.text_field :prénom, class: 'input input-bordered input-sm w-full', required: true %>
  </div>

  <div class="mt-4">
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email, class: 'input input-bordered input-sm w-full', required: true %>
  </div>

  <div class="mt-4">
    <%= form.label :adresse, style: "display: block" %>
    <%= form.text_area :adresse, class: 'textarea textarea-bordered textarea-sm w-full', rows: 4 %>
  </div>

  <div class="mt-4">
    <%= form.label :tag_list, "Groupes", style: "display: block" %>
    <%= form.select :tag_list, options_from_collection_for_select(@tags, :name, :name, user.tags.map(&:name)), multiple: true %>
  </div>

  <% if user.new_record? %>
    <div class="mt-4">
      <%= form.label :password, style: "display: block" %>
      <%= form.password_field :password, class: 'input input-bordered input-sm w-full' %>
    </div>
    <div class="mt-4">
      <%= form.label :password_confirmation, style: "display: block" %>
      <%= form.password_field :password_confirmation, class: 'input input-bordered input-sm w-full' %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit "Enregistrer", class: "btn btn-primary btn-outline btn-sm my-4" %>
  </div>
<% end %>

<script>
  // slimselect
  new SlimSelect({
    select: '#user_tag_list',
    settings: {
      searchPlaceholder: 'Recherche',
      searchText: 'Pas de résultat',
      searchingText: 'Recherche...',
      placeholderText: 'Choisissez un ou plusieurs groupes',
      allowDeselect: true,
    },
    events: {
      addable: function (value) {
        return value
      }
    }
  })
</script>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="mt-4 pb-4 border-b border-gray-200">

  <%= link_to user_path(user), class:'text-2xl font-bold text-primary hover:underline' do %>
    <% if user.admin? %>
      <span class="material-symbols-outlined text-secondary" title="Administrateur de l'organisation">
        local_police
      </span>
    <% end %>
    <%= user.nom_prénom %>
  <% end %>

  <br>
  <span class="text-secondary"><%= user.email %></span>

  <p class="mt-4">
    Groupes :
    <% user.tags.each do |tag| %>
      <span class="badge"><%= tag.name.humanize %></span>
    <% end %>
  </p>

  <p class="mt-4">
    <%= link_to_if user.presences.count.positive?, pluralize(user.presences.count, 'émargement', plural: 'émargements'), presences_path(user_id: user.id), class: 'text-primary hover:underline', title: "Voir tous les émargements de ce participant." %>
  </p>
  
</div>

app/views/users/edit.html.erb
<h1 class="text-4xl font-bold mb-6"><%= page_title!("Modification Participant") %></h1>

<div class="max-w-96">
  <%= render "form", user: @user %>
</div>

<%= link_to "Retour", users_path, class:'btn btn-sm' %>

app/views/users/index.html.erb
<div class="flex flex-wrap justify-between">
  <h1 class="text-4xl font-bold mb-4">
    <%= page_title!("Participants") %>
  </h1>
  
  <div>
    <%= link_to "Ajouter Participant", admin_create_new_participant_path, class:'btn btn-primary btn-outline btn-lg hover:shadow-xl hover:!text-white' %>
    <% if policy(:admin).import? %>
      <%= link_to "Importer", admin_import_path, class:'btn btn-primary btn-outline btn-lg hover:shadow-xl hover:!text-white' %>
    <% else %>
      <%= link_to "Importer", admin_premium_path(alert: true), class:'btn btn-primary btn-outline btn-lg disabled-element ' %>
    <% end %>
    <%= link_to "+Administrateur", admin_create_new_admin_path, class:'btn btn-primary btn-outline btn-lg hover:shadow-xl hover:!text-white' %>
  </div>
</div>

<%= form_tag request.path, method: :get do %>
  <div class="flex flex-wrap items-end gap-4">
    <div class="max-w-72">
      <%= label_tag :search, "Rechercher" %>
      <%= text_field_tag :search, params[:search], include_blank:true, onchange:'this.form.submit()', class: 'input input-bordered input-sm w-full', placeholder: 'Nom/Prénom/Email' %>
    </div>

    <div class="max-w-72 w-full">
      <%= label_tag :assemblee_id, "Session" %>
      <%= select_tag :assemblee_id, options_from_collection_for_select(@assemblees, :id, :nom, params[:assemblee_id]), include_blank: true, onchange: 'this.form.submit()' %>
    </div>
    <%# label_tag :admin, "Admin" %>
    <%# check_box_tag :admin, params[:admin], params[:admin], class: 'checkbox', onchange: 'this.form.submit()' %>
    <div>
      <%= render TagCloudComponent.new(tags: @tags) %>
    </div>
  </div>
<% end %>

<div class="divider"></div>

<div id="users">
  <%= render @users %>
</div>


<p class="mt-8">Affichage de <%= pluralize(@users.count, 'participant', plural: 'participants') %> sur <%= current_user.organisation.users.count %> au total</p>

<script>
  new SlimSelect({
    select: '#assemblee_id',
    settings: {
      searchPlaceholder: 'Recherche',
      searchText: 'Pas de résultat',
      searchingText: 'Recherche...',
      placeholderText: 'Filtrer par session',
      allowDeselect: true
    }
  })
</script>

app/views/users/new.html.erb
<h1 class="text-4xl font-bold text-primary mb-6"><%= page_title!("Nouveau Participant") %></h1>

<div class="max-w-96">
  <%= render "form", user: @user %>
</div>

<br>

<div>
  <%= link_to "Retour", users_path, class:'btn btn-sm' %>
</div>

app/views/users/show.html.erb
<h1 class="text-4xl font-bold text-primary my-4 ">
  <%= page_title!(@user.nom_prénom) %>
  <% if @user.admin %>
    <span class="material-symbols-outlined text-secondary">
      local_police
    </span>
  <% end %>
</h1>

<% @user.tags.each do |tag| %>
  <%= link_to(tag.name.humanize, users_path(tag:tag.name), class: 'badge badge-ghost') %>
<% end %>

<p class="mt-8">
  <strong>Email :</strong>
  <%= @user.email %>
</p>

<p class="mt-4">
  <strong>Adresse :</strong>
  <%= @user.adresse %>
</p>

<p class="mt-4">
  <strong>Nombre d'émargements :</strong>
  <%= @user.presences.count %>
</p>

<% unless @user.sign_in_count.zero? %>
  <p class="mt-8 mb-4">
    Connexion actuelle : 
    le <%= l(@user.current_sign_in_at) %> 
    | Il y a <%= time_ago_in_words(@user.current_sign_in_at) %>
  </p>
  <p class="mb-4">
    Dernière connexion : 
    le <%= l(@user.last_sign_in_at) %> 
    | Il y a <%= time_ago_in_words(@user.last_sign_in_at) %>
  </p>
  <p>
    Nbr connexions : <%= @user.sign_in_count %> 
  </p>
<% end %>
<div class="flex flex-wrap gap-4 mt-8">
  <%= link_to "Modifier", edit_user_path(@user), class:'btn btn-primary btn-outline btn-sm' %>
  <%= button_to @user, method: :delete, data:{turbo_confirm: "Êtes-vous certain(e) de vouloir supprimer ce participant ?"}, class:'btn btn-error btn-outline btn-sm', disabled: @user.presences.any? do %>
    <span class="material-symbols-outlined">
      delete
    </span>
  <% end %>
  <%= link_to "Retour", users_path, class:'btn btn-outline btn-sm' %>
</div>