config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root 'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # Mount Mission Control Job's engine where you wish to have it accessible
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :assemblees do
    collection do
      get :import
      post :import_do
    end
    member do
      get :envoyer_lien_gestionnaire
    end
  end
  resources :users
  resources :presences, only: %i[ index destroy ]
  resources :organisations, only: %i[ edit update ]
  resources :mail_logs, only: %i[ index show ]

  namespace :admin do
    get :index
    get :signature_collective
    post :signature_collective_do
    get :signature_individuelle
    post :signature_individuelle_do
    get :import
    post :import_do
    get :audits
    get :premium
    get :create_new_admin
    post :create_new_admin_do
    get :create_new_participant
    post :create_new_participant_do
    get :fake_signatures_detector
    get :fake_signature_detector
    get :launch_fake_signature_detector
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"

  # Defines the root path route ("/")
  root "presences#new"
end

app/models/assemblee.rb
class Assemblee < ApplicationRecord
  extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

  include Workflow
  include WorkflowActiverecord

  audited

  acts_as_taggable_on :tags

  belongs_to :user
  belongs_to :organisation
  has_many :presences, dependent: :destroy

  validates :nom, :début, :durée, presence: :true

  after_save :update_fin

  scope :ordered, -> { order(updated_at: :desc) }

  # WORKFLOW
  # 
    
  ATTENTE   = 'attente'
  EN_COURS  = 'en cours'
  COMPLET   = 'complet'
  INCOMPLET = 'incomplet'
  ARCHIVE   = 'archivé'

  workflow do
    state ATTENTE,  meta: {style: 'badge badge-lg text-primary'}
    state EN_COURS, meta: {style: 'badge badge-lg text-error'}
    state COMPLET,  meta: {style: 'badge badge-lg text-success'}
    state INCOMPLET,meta: {style: 'badge badge-lg text-warning'}
    state ARCHIVE,  meta: {style: 'badge badge-lg text-secondary'}
  end

  # pour que le changement de 'workflow_state' se voit dans l'audit trail
  def persist_workflow_state(new_value)
    self[:workflow_state] = new_value
    save!
  end

  def self.workflow_state_humanized
    self.workflow_spec.states.keys.map{|i| i.to_s.humanize }
  end

  #
  # Decorators ------------------------------------
  #

  def style
    self.current_state.meta[:style]
  end

  def in_progress?
    (self.début < DateTime.now + 10.minutes) && (self.fin > DateTime.now)
  end

  def related_users
    ids = []
    self.tags.each do |tag|
      ids << self.organisation.users.tagged_with(tag).pluck(:id)
    end
    return ids.flatten.uniq
  end

  def qrcode(url)
    RQRCode::QRCode.new(url).as_svg(
                color: "000",
                shape_rendering: "crispEdges",
                module_size: 3,
                standalone: true,
                use_path: true)
  end

  def horaires
    "#{ I18n.l(self.début, format: "%d %b") } #{self.début.hour}h#{self.début.min unless self.début.min == 0} -> #{self.fin.hour}h#{self.fin.min unless self.fin.min == 0}"
  end

  def horaires_medium
    "#{I18n.l(self.début, format: "%A %d %b")} #{self.début.hour}h#{self.début.min unless self.début.min == 0} -> #{self.fin.hour}h#{self.fin.min unless self.fin.min == 0}"
  end

  def horaires_long
    "#{I18n.l(self.début, format: :custom2)} #{self.début.hour}h#{self.début.min unless self.début.min == 0} -> #{self.fin.hour}h#{self.fin.min unless self.fin.min == 0}"
  end

  def nom_long
    "#{self.nom} [#{self.horaires_medium}]"
  end

  def users_not_signed
    # Liste des utilisateurs des groupes de la sessino qui n'ont pas signé
    User.where(id: self.related_users)
        .where.not(id: self.presences.pluck(:user_id))
        .ordered
  end

  private

  def update_fin
    self.update_column(:fin, self.début + self.durée.to_f.hours)
  end

  def slug_candidates
		[SecureRandom.uuid]
	end
end

app/controllers/assemblees_controller.rb
class AssembleesController < ApplicationController
  before_action :set_assemblee, only: %i[ show edit update destroy envoyer_lien_gestionnaire ]
  before_action :is_user_authorized
  before_action :set_tags, only: %i[ new edit import ]

  # GET /assemblees or /assemblees.json
  def index
    @assemblees = current_user.organisation.assemblees.ordered
    @tags = @assemblees.tag_counts_on(:tags).order(:taggings_count).reverse

    if params[:search].present?
      @assemblees = @assemblees.where("nom ILIKE :search OR adresse ILIKE :search", {search: "%#{params[:search]}%"})
    end

    if params[:tags].present?
      @assemblees = @assemblees.tagged_with(params[:tags].reject(&:blank?))
      session[:tags] = params[:tags]
    else
      session[:tags] = params[:tags] = []
    end

    if params[:debut].present?
      if params[:fin].present?
        @assemblees = @assemblees.where("DATE(début) BETWEEN ? AND ?", params[:debut], params[:fin])
      else
        @assemblees = @assemblees.where("DATE(début) = ?", params[:debut])
      end
    end

    if params[:workflow_state].present?
      @assemblees = @assemblees.where("assemblees.workflow_state = ?", params[:workflow_state].to_s.downcase)
    end

    respond_to do |format|
      format.html

      format.ics do
        filename = "Export_iCalendar_#{Date.today.to_s}"
        response.headers['Content-Disposition'] = 'attachment; filename="' + filename + '.ics"'
        headers['Content-Type'] = "text/calendar; charset=UTF-8"
        render plain: AssembleesToIcalendar.new(@assemblees).call
      end
    end
  end

  # GET /assemblees/1 or /assemblees/1.json
  def show
    respond_to do |format|
      format.html

      format.pdf do
        pdf = AssembleePdf.new
        pdf.convocation(@assemblee)

        send_data pdf.render,
            filename: "#{@assemblee.nom}-#{l @assemblee.début.to_date} #{DateTime.now}.pdf",
            type: 'application/pdf',
            disposition: 'inline'
      end
    end
  end

  # GET /assemblees/new
  def new
    @assemblee = Assemblee.new
    if params[:assemblee_id].present?
      assemblee_old = Assemblee.find_by(slug: params[:assemblee_id])
      @assemblee.nom = assemblee_old.nom
      @assemblee.tags = assemblee_old.tags
      @assemblee.début = assemblee_old.début
      @assemblee.fin = assemblee_old.fin
      @assemblee.durée = assemblee_old.durée
      @assemblee.adresse = assemblee_old.adresse
      @assemblee.automatique = assemblee_old.automatique
      @assemblee.notifier_participants = assemblee_old.notifier_participants            
    else
      @assemblee.début = DateTime.now.change(min: 0, sec: 0) + 1.hour
      @assemblee.durée = 2
      @assemblee.automatique = true
    end
  end

  # GET /assemblees/1/edit
  def edit
  end

  # POST /assemblees or /assemblees.json
  def create
    @assemblee = Assemblee.new(assemblee_params)
    @assemblee.tag_list.add(params[:assemblee][:tags])
    @assemblee.organisation = current_user.organisation
    @assemblee.user = current_user

    respond_to do |format|
      if @assemblee.save
        unless Rails.env.development?
          Events.instance.publish('assemblee.created', payload: {assemblee_id: @assemblee.id})
        end
        format.html do 
          redirect_to current_user.organisation.step < 4 ? admin_index_path : assemblees_url
          flash[:notice] = "Session créée avec succès."
        end
        format.json { render :show, status: :created, location: @assemblee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assemblee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assemblees/1 or /assemblees/1.json
  def update
    respond_to do |format|
      if @assemblee.update(assemblee_params)
        @assemblee.tag_list = params[:assemblee][:tags]
        @assemblee.save
        format.html { redirect_to assemblees_url, notice: "Session modifiée avec succès." }
        format.json { render :show, status: :ok, location: @assemblee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assemblee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assemblees/1 or /assemblees/1.json
  def destroy
    @assemblee.destroy!

    respond_to do |format|
      format.html { redirect_to assemblees_url, notice: "Session supprimée avec succès." }
      format.json { head :no_content }
    end
  end

  def envoyer_lien_gestionnaire
    EnvoyerLienSignatureCollectiveJob.perform_later(@assemblee, current_user.id)
    redirect_to assemblees_path, notice: "Lien de signature envoyé au gestionnaire."
  end

  def import
  end

  def import_do
    assemblees_infos = params[:assemblees].split("\r\n")
    assemblees_imported = ImportAssemblees.new(assemblees_infos, current_user, params[:groupes]).call
    redirect_to assemblees_path, notice: "#{assemblees_imported} session(s) importée(s) sur #{assemblees_infos.count}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assemblee
      @assemblee = Assemblee.find_by(slug: params[:id])
    end
    
    def set_tags
      @tags = current_user.organisation.tags
    end

    # Only allow a list of trusted parameters through.
    def assemblee_params
      params.require(:assemblee).permit(:nom, :début, :durée, :adresse, :user_id, :tag_list, :automatique, :notifier_participants, :workflow_state)
    end

    def is_user_authorized
      authorize @assemblee ? @assemblee : Assemblee
    end

end

app/helpers/assemblees_helper.rb
module AssembleesHelper
end

app/views/assemblees/_assemblee.html.erb
<div id="<%= dom_id assemblee %>" class="mt-4 pb-4 border-b border-gray-200">
  <div class="flex flex-wrap gap-8">
    <div>
      <p class="text-3xl font-bold text-primary hover:underline">
        <%= assemblee.nom.humanize %>
      </p>
      
      <p class="font-bold">
        <%= assemblee.horaires_long %>
        <% if assemblee.début > DateTime.now %>
          <span class="text-warning italic">
            (début de session dans <%= time_ago_in_words assemblee.début %>)
          </span>
        <% elsif assemblee.in_progress? %>
          <span class="text-error italic">
            (fin de session dans <%= time_ago_in_words assemblee.fin %>)
          </span>
        <% end %>
      </p>

      <p class="mt-4">
        Groupes : <% assemblee.tags.each do |tag| %>
          <span class="badge"><%= link_to tag.name.humanize, users_path(tags: [tag.name]), class: "hover:underline" %></span>
        <% end %>
        |         
        Gestionnaire : <%= assemblee.user.nom_prénom %> (<%= assemblee.user.email %>)
      </p>

      <p class="my-4">
        Statut : 
        <span class="text-nowrap font-bold <%= assemblee.style %>">
          <%= assemblee.workflow_state.humanize %>
        </span>
        |
        Émargements :
        <%= link_to assemblee.presences.count, presences_path(assemblee_id: assemblee.id), class: 'text-primary hover:underline' %>
        /
        <%= link_to "#{assemblee.related_users.count} participant(s)", users_path(assemblee_id: assemblee.id), class: 'text-primary hover:underline' %>
      </p>

      <div class="flex flex-wrap gap-2 mt-6">
        <%= link_to "Modifier", edit_assemblee_path(assemblee), class:'btn btn-primary btn-outline btn-sm' %>
        <%= link_to "Copier", new_assemblee_path(assemblee_id: assemblee), class:'btn btn-success btn-outline btn-sm' %>

        <%= link_to "Générer les convocations", assemblee_path(assemblee, format: :pdf), class:'btn btn-secondary btn-outline btn-sm', target: "_blank", title: "Générer les convocations (PDF)" %>
        <% if assemblee.fin > DateTime.now %>
          <%= link_to "Envoyer le lien au gestionnaire", envoyer_lien_gestionnaire_assemblee_path(assemblee), class: 'btn btn-warning btn-outline btn-sm', title: "Envoyer au gestionnaire un mail contenant le lien public vers la feuille d'émargement des présences" %>
        <% end %>
        <%= button_to assemblee, method: :delete, data: {turbo_confirm: "Êtes-vous certain(e) de vouloir supprimer cette session ? Cela supprimera aussi les signatures liées" }, class: 'btn btn-error btn-outline btn-sm' do %>
          <span class="material-symbols-outlined">
            delete
          </span>
        <% end %>
      </div>
    </div>

    <% if assemblee.in_progress? %>
      <div class="self-end shadow p-4">
        <%= raw assemblee.qrcode(admin_signature_collective_url(assemblee_id: assemblee.slug)) %>
        <%= link_to "Signer maintenant !", admin_signature_collective_url(assemblee_id: assemblee.slug), class: 'btn btn-outline text-success mt-4 w-full', target: '_blank', title: "Lancer la session de signature collective ou flasher le Qr-code pour émarger à partir d'un autre appareil (Tablette)" %>
      </div>
    <% end %>

  </div>
</div>

app/views/assemblees/_form.html.erb
<%= form_with(model: assemblee) do |form| %>
  <% if assemblee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(assemblee.errors.count, "error") %> prohibited this assemblee from being saved:</h2>

      <ul>
        <% assemblee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      
    </div>
  <% end %>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :nom, class: 'input input-bordered input-sm w-full', required: true, placeholder: 'ex: Commission Mobilité' %>
  </div>

  <div class="mt-4">
    <%= form.label :tags, "Groupes d'intérêt", style: "display: block" %>
    <%= form.select :tags, options_from_collection_for_select(@tags, :name, :name, assemblee.tags.map(&:name)), multiple: true %>
  </div>

  <div class="mt-4">
    <%= form.label :début, style: "display: block" %>
    <%= form.datetime_field :début, class: 'input input-bordered input-sm w-full', required: true %>
  </div>

  <div class="mt-4">
    <%= form.label :durée, "Durée (h)", style: "display: block" %>
    <%= form.number_field :durée, step: :any, class: 'input input-bordered input-sm w-full' %>
  </div>

  <div class="mt-4">
    <%= form.label "Lieu (adresse)", style: "display: block" %>
    <%= form.text_area :adresse, class: 'textarea textarea-bordered textarea-xs w-full' %>
  </div>

  <div class="mt-4" title="Envoyer automatiquement le lien pour une session collective de signatures (généralement via un partage de tablette) 10 minutes avant le début de la session">
    <%= form.check_box :automatique %>
    <%= form.label :automatique, "Envoyer le lien collectif à l'admin de la session ? " %>
  </div>

  <div class="mt-4" title="Envoyer automatiquement le lien individuel à tous les participants 10 minutes avant le début de la session ?">
    <%= form.check_box :notifier_participants %>
    <%= form.label :notifier_participants, "Envoyer le lien individuel aux participants ?" %>
  </div>

  <% if assemblee.persisted? %>
    <div class="mt-4">
      <%= form.label :workflow_state, "Statut", style: "display: block" %>
      <%= form.select :workflow_state, options_for_select(Assemblee.workflow_spec.states.keys, assemblee.workflow_state), {}, class: 'input input-bordered input-sm w-full', required: true  %>
    </div>
  <% end %>

  <div>
    <%= form.submit "Enregistrer", class:'btn btn-primary btn-outline w-full mt-8 mb-4' %>
    <%= link_to "Retour", assemblees_path, class:'link' %>
  </div>
<% end %>

<script>
  // slimselect
  new SlimSelect({
    select: '#assemblee_tags',
    settings: {
      searchPlaceholder: 'Recherche',
      searchText: 'Pas de résultat',
      searchingText: 'Recherche...',
      placeholderText: 'Choisissez un ou plusieurs groupes',
      allowDeselect: true,
    },
    events: {
      addable: function (value) {
        return value
      }
    }
  })
</script>

app/views/assemblees/edit.html.erb
<div class="mx-auto md:w-1/4 w-full">
  <h1 class="text-4xl font-bold mb-6 text-nowrap">
    <%= page_title!("Modification Session") %>
  </h1>

  <div class="max-w-96 md:max-w-lg">
    <%= render "form", assemblee: @assemblee %>
  </div>
</div>

app/views/assemblees/import.html.erb
<div class="mx-auto md:w-1/3 w-full">
  <h1 class="text-4xl font-bold text-nowrap mb-6">
    <%= page_title!("Importer des Sessions") %>
  </h1>

  <%= form_tag({action: "import_do", method: :post}, multipart: true) do %>
    <div>
      <%= label_tag :assemblees, "Données à importer (Nom, Date, Heure, Durée), séparées par une virgule ou un point-virgule" %>
      <%= text_area_tag :assemblees, nil, 
                        rows: 7, 
                        class:"textarea textarea-bordered textarea-sm w-full shadow", 
                        required: true, 
                        placeholder: "Réunion de Mars, 01/03/2024, 09:30, 2.5\r\nRéunion d'Avril;13/04/2024;12:15;1\r\nRéunion de Novembre à minuit;25/11/2024;00:00;2" %>
      <label>
        <span class="label-text-alt">
          Les sessions doivent être séparées par un retour à la ligne. Elles doivent contenir un nom, une date au format JJ/MM/AAAA, une heure de début au format HH:MM et une durée en heure (ex: 2.5 pour 2 heures 30 minutes).
        </span>
      </label>
    </div>
    
    <div class="mt-4">
      <%= label_tag :groupes, "Groupes d'intérêt", style: "display: block" %>
      <%= select_tag :groupes, options_from_collection_for_select(@tags, :name, :name), multiple: true %>
    </div>

    <div>
      <%= submit_tag "Lancer l'importation", class: "btn btn-primary btn-outline w-full my-4", 'data-turbo': false %>
      <%= link_to "Retour", root_path, class: "link" %>
    </div>
  <% end %>
</div>

<script>
  // slimselect
  new SlimSelect({
    select: '#groupes',
    settings: {
      searchPlaceholder: 'Recherche',
      searchText: 'Pas de résultat',
      searchingText: 'Recherche...',
      placeholderText: 'Choisissez un ou plusieurs groupes',
      allowDeselect: true,
    },
    events: {
      addable: function (value) {
        return value
      }
    }
  })
</script>

app/views/assemblees/index.html.erb
<div class="flex flex-wrap justify-between">
  <h1 class="text-4xl font-bold"><%= page_title!("Sessions") %></h1>
  <div>
    <%= link_to "Nouvelle Session", new_assemblee_path, class:'btn btn-primary btn-outline btn-lg hover:shadow-xl hover:!text-white' %>
    <%= link_to "Importer", import_assemblees_path, class:'btn btn-primary btn-outline btn-lg hover:shadow-xl hover:!text-white' %>
  </div>
</div>

<%= form_tag request.path, method: :get do %>
  <div class="flex flex-wrap items-end gap-4">
    <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/6">
      <%= label_tag :search, "Rechercher" %>
      <%= text_field_tag :search, params[:search], include_blank:true, onchange:'this.form.submit()', class: 'input input-bordered input-sm w-full', placeholder: 'Nom/Adresse' %>
    </div>

    <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/6">
      <%= label_tag :debut, 'Du' %>
      <%= date_field_tag :debut, params[:debut], onchange: 'this.form.submit()', class: 'input input-bordered input-sm w-full' %>
    </div>

    <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/6">
      <%= label_tag :fin, 'Fin' %>
      <%= date_field_tag :fin, params[:fin], onchange: 'this.form.submit()', class: 'input input-bordered input-sm w-full' %>
    </div>

    <div class="w-full m:w-1/2 md:w-1/3 lg:w-1/6">
      <%= label_tag :workflow_state, "Statut" %>
      <%= select_tag :workflow_state, 
                      options_for_select(Assemblee.workflow_state_humanized, params[:workflow_state]), 
                      include_blank: true,
                      class: 'select select-bordered select-sm w-full', 
                      onchange: 'this.form.submit()' %>
    </div>

    <div>
      <%= render TagCloudComponent.new(tags: @tags) %>
    </div>
  </div>
<% end %>

<div class="divider"></div>

<div id="assemblees">
  <%= render @assemblees %>
</div>

<p class="mt-8 mb-2">Affichage de <%= pluralize(@assemblees.count, 'session', plural: 'sessions') %> sur <%= current_user.organisation.assemblees.count %> au total</p>

<% if @assemblees.any? %>
  <%= link_to url_for(params.permit!.merge(format: :ics)), class: "text-primary hover:underline" do %>
    Exporter les sessions vers votre calendrier personnel (Google Agenda, Apple Calendar, Outlook, ...)
  <% end %>
<% end %>

app/views/assemblees/new.html.erb
<div class="mx-auto md:w-1/4 w-full">

  <h1 class="text-4xl font-bold mb-6">
    <%= page_title!("Nouvelle Session") %>
  </h1>

  <div class="max-w-96 md:max-w-lg">
    <%= render "form", assemblee: @assemblee %>
  </div>
  
</div>

app/views/assemblees/show.html.erb
<%= render @assemblee %>